# Generated by Django 5.1.1 on 2024-10-25 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_service_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
