# Generated by Django 5.1.1 on 2024-10-12 14:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='dob',
            field=models.DateField(default=datetime.datetime(2024, 10, 12, 14, 18, 42, 322506, tzinfo=datetime.timezone.utc)),
        ),
    ]
