# Generated by Django 5.1.1 on 2024-10-20 05:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customer_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='dob',
            field=models.DateField(default=datetime.datetime(2024, 10, 20, 5, 38, 39, 342055, tzinfo=datetime.timezone.utc)),
        ),
    ]
