# Generated by Django 5.1.1 on 2024-10-25 01:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customer_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='dob',
            field=models.DateField(default=datetime.datetime(2024, 10, 25, 1, 54, 49, 600254, tzinfo=datetime.timezone.utc)),
        ),
    ]
