# Generated by Django 5.1.1 on 2024-10-25 02:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customer_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='dob',
            field=models.DateField(default=datetime.datetime(2024, 10, 25, 2, 28, 35, 692643, tzinfo=datetime.timezone.utc)),
        ),
    ]
